name: Pull-request pre-validation

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pre_validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build dependencies with Maven
      run: mvn clean validate -Pbootstrap

    #- name: Execute unit-testing and SCA with Quality Gate
    #  run: |
    #   export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
    #   mvn clean test -Pvalidate

    - name: Execute unit-testing
      run: |
       mvn clean test
